server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: cloud-payment-service #支付模块
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://39.108.135.34:3307/HAND?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hand.cloud.entities
  config-location: classpath:mybatis_config.xml

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,
                   # http://eureka2.com:7002/eureka/
  instance:
    instance-id: 支付模块_8001
    prefer-ip-address: true

    lease-renewal-interval-in-seconds: 1  #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到心跳后等待时间上限，单位为秒