server:
  port: 7002

eureka:
  instance:
    hostname: eureka2.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心去注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

    #设置与EurekaServer交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/



  server:
    enable-self-preservation: false #关闭自我保护机制，保证不可用服务及时被禁止
    a-s-g-cache-expiry-timeout-ms: 2000